# Generated by Django 4.0.1 on 2022-02-01 02:52

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, verbose_name='Nome')),
                ('sinopse', models.CharField(max_length=128, verbose_name='Sinopse')),
                ('classificacao', models.CharField(choices=[('Livre', 'Livre'), ('10+', '10+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+')], max_length=32)),
                ('duracao', models.CharField(max_length=16, verbose_name='Duração')),
                ('capa', stdimage.models.StdImageField(upload_to='imagens', verbose_name='Capa do Filme')),
                ('trailer', models.URLField(max_length=100, verbose_name='Trailer do Filme')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCartaz', models.DateTimeField(verbose_name='Data do Cartaz')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Assentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupado', models.BooleanField(default=False)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.sessao')),
            ],
        ),
    ]
