# Generated by Django 4.0.1 on 2022-01-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10+', '10+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+')], max_length=32),
        ),
    ]
